spring.application.name=HomeworkStrateguistSB-Gradle
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Caching (Helpful for Hackathon performance)
spring.cache.type=simple

# JSON Formatting for easier debugging
spring.jackson.serialization.indent_output=true

# If the environment variable exists, use it. Otherwise, use empty string.
canvas.api.token=${CANVAS_ACCESS_TOKEN:}
canvas.api.domain=${CANVAS_DOMAIN:canvas.socccd.edu}